const SET_CART = "SET_CART"
const ADD_TO_CART = "ADD_TO_CART";
const REMOVE_FROM_CART = "REMOVE_FROM_CART";
const CART_RESET = "CART_RESET";

export {SET_CART, ADD_TO_CART, REMOVE_FROM_CART, CART_RESET};